In [2]:
%matplotlib inline

import time
import pandas
import random
import numpy
import matplotlib.pyplot as plt
import seaborn; seaborn.set_style('whitegrid')
import itertools

from pomegranate import *

random.seed(0)
numpy.random.seed(0)
numpy.set_printoptions(suppress=True)

%load_ext watermark
%watermark -m -n -p numpy,scipy,pomegranate


numpy      : 1.22.3
scipy      : 1.7.3
pomegranate: 0.14.4

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 5.10.16.3-microsoft-standard-WSL2
Machine     : x86_64
Processor   : x86_64
CPU cores   : 8
Architecture: 64bit



In [3]:
model = NormalDistribution(5, 1)

print(model.probability([4., 6., 7.]))
print(model.log_probability([4., 6., 7.]))


[0.24197072 0.24197072 0.05399097]
[-1.41893853 -1.41893853 -2.91893853]


In [4]:
model.sample(n=10)

array([6.76405235, 5.40015721, 5.97873798, 7.2408932 , 6.86755799,
       4.02272212, 5.95008842, 4.84864279, 4.89678115, 5.4105985 ])

In [5]:
X = numpy.random.normal(7, 2, size=(100,))

model.fit(X)
model

{
    "class" : "Distribution",
    "name" : "NormalDistribution",
    "parameters" : [
        7.036955079959913,
        2.0668514243367655
    ],
    "frozen" : false
}

In [6]:
X = numpy.random.normal(8, 1.5, size=(100,))

model.summarize(X)
model

{
    "class" : "Distribution",
    "name" : "NormalDistribution",
    "parameters" : [
        7.036955079959913,
        2.0668514243367655
    ],
    "frozen" : false
}

In [7]:
model.from_summaries()
model

{
    "class" : "Distribution",
    "name" : "NormalDistribution",
    "parameters" : [
        8.068146018374335,
        1.4490322240381275
    ],
    "frozen" : false
}

In [14]:
X = numpy.random.normal(3, 0.2, size=(100,))

model.summarize(X)
model.clear_summaries()
model.from_summaries()
model

{
    "class" : "Distribution",
    "name" : "NormalDistribution",
    "parameters" : [
        8.068146018374335,
        1.4490322240381275
    ],
    "frozen" : false
}

In [15]:
X = numpy.random.normal(6, 1, size=(250, 1))

model = NormalDistribution.from_samples(X)
model

{
    "class" : "Distribution",
    "name" : "NormalDistribution",
    "parameters" : [
        5.9252675264933385,
        0.9638666428077448
    ],
    "frozen" : false
}